// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddAssumptionInput struct {
	DecisionID string  `json:"decisionId"`
	Statement  string  `json:"statement"`
	Confidence float64 `json:"confidence"`
}

type AddTeamMemberInput struct {
	TeamID string `json:"teamId"`
	UserID string `json:"userId"`
	Role   Role   `json:"role"`
}

type AddTeamMemberPayload struct {
	Membership *Membership `json:"membership,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

// An assumption that underpins a decision, with a confidence in [0, 1].
type Assumption struct {
	ID         string     `json:"id"`
	Statement  string     `json:"statement"`
	Confidence float64    `json:"confidence"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	Decision   *Decision  `json:"decision"`
	Evidence   []Evidence `json:"evidence"`
}

type AssumptionPayload struct {
	Assumption *Assumption `json:"assumption,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

type AttachEvidenceInput struct {
	AssumptionID string             `json:"assumptionId"`
	SourceType   EvidenceSourceType `json:"sourceType"`
	SourceURL    *string            `json:"sourceUrl,omitempty"`
	Content      string             `json:"content"`
}

// The result of an authentication mutation: tokens plus the authenticated user.
type AuthPayload struct {
	User            *User       `json:"user,omitempty"`
	AccessToken     *string     `json:"accessToken,omitempty"`
	AccessExpiresAt *time.Time  `json:"accessExpiresAt,omitempty"`
	RefreshToken    *string     `json:"refreshToken,omitempty"`
	UserErrors      []UserError `json:"userErrors"`
}

// The result of a bias-detection request.
type BiasReport struct {
	Summary string         `json:"summary"`
	Biases  []DetectedBias `json:"biases"`
}

// One decile of a calibration (reliability) curve.
type CalibrationBin struct {
	// The decile index, 1..10, of predicted probability.
	Bucket int `json:"bucket"`
	// Average predicted probability of forecasts in the bin.
	MeanPredicted float64 `json:"meanPredicted"`
	// Fraction of those forecasts that actually succeeded, in [0, 1].
	ObservedFrequency float64 `json:"observedFrequency"`
	// Number of forecasts in the bin.
	SampleSize int `json:"sampleSize"`
}

// The full set of calibration bins for a team, ordered by bucket.
type CalibrationReport struct {
	Bins []CalibrationBin `json:"bins"`
}

type ChangeMemberRoleInput struct {
	TeamID string `json:"teamId"`
	UserID string `json:"userId"`
	Role   Role   `json:"role"`
}

type ChangeMemberRolePayload struct {
	Membership *Membership `json:"membership,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

type CreateDecisionInput struct {
	TeamID      string `json:"teamId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type CreatePredictionInput struct {
	DecisionID  string     `json:"decisionId"`
	Statement   string     `json:"statement"`
	Probability float64    `json:"probability"`
	ResolvesAt  *time.Time `json:"resolvesAt,omitempty"`
}

type CreateTeamInput struct {
	Name string `json:"name"`
}

type CreateTeamPayload struct {
	Team       *Team       `json:"team,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

// A decision: the root aggregate that assumptions, predictions, and an outcome hang from.
type Decision struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Status      DecisionStatus `json:"status"`
	DecidedAt   *time.Time     `json:"decidedAt,omitempty"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	Owner       *User          `json:"owner"`
	Team        *Team          `json:"team"`
	Assumptions []Assumption   `json:"assumptions"`
	Predictions []Prediction   `json:"predictions"`
	Outcome     *Outcome       `json:"outcome,omitempty"`
}

type DecisionConnection struct {
	Edges      []DecisionEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type DecisionEdge struct {
	Node   *Decision `json:"node"`
	Cursor string    `json:"cursor"`
}

type DecisionPayload struct {
	Decision   *Decision   `json:"decision,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

// Shared payload for mutations that delete an entity.
type DeletePayload struct {
	Success    bool        `json:"success"`
	UserErrors []UserError `json:"userErrors"`
}

// A single cognitive bias flagged in a piece of text.
type DetectedBias struct {
	Name        string `json:"name"`
	Explanation string `json:"explanation"`
}

// Evidence attached to an assumption that supports or challenges it.
type Evidence struct {
	ID         string             `json:"id"`
	SourceType EvidenceSourceType `json:"sourceType"`
	SourceURL  *string            `json:"sourceUrl,omitempty"`
	Content    string             `json:"content"`
	CreatedAt  time.Time          `json:"createdAt"`
	UpdatedAt  time.Time          `json:"updatedAt"`
	Assumption *Assumption        `json:"assumption"`
}

type EvidencePayload struct {
	Evidence   *Evidence   `json:"evidence,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// A user's membership of a team and the role they hold within it.
type Membership struct {
	Team      *Team     `json:"team"`
	User      *User     `json:"user"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

// The final result recorded for a decision.
type Outcome struct {
	ID         string    `json:"id"`
	Summary    string    `json:"summary"`
	Success    bool      `json:"success"`
	ResolvedAt time.Time `json:"resolvedAt"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	Decision   *Decision `json:"decision"`
}

type OutcomePayload struct {
	Outcome    *Outcome    `json:"outcome,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

// Relay-style pagination metadata for a connection.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

// A forecast attached to a decision, with a probability in [0, 1].
type Prediction struct {
	ID          string     `json:"id"`
	Statement   string     `json:"statement"`
	Probability float64    `json:"probability"`
	ResolvesAt  *time.Time `json:"resolvesAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	Decision    *Decision  `json:"decision"`
}

type PredictionPayload struct {
	Prediction *Prediction `json:"prediction,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

type Query struct {
}

type RecordOutcomeInput struct {
	DecisionID string    `json:"decisionId"`
	Summary    string    `json:"summary"`
	Success    bool      `json:"success"`
	ResolvedAt time.Time `json:"resolvedAt"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RemoveTeamMemberInput struct {
	TeamID string `json:"teamId"`
	UserID string `json:"userId"`
}

type RemoveTeamMemberPayload struct {
	Success    bool        `json:"success"`
	UserErrors []UserError `json:"userErrors"`
}

type Subscription struct {
}

// A team that groups users and scopes their decisions.
type Team struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
	Members   []Membership `json:"members"`
}

// Headline decision-quality summary for a team.
type TeamMetrics struct {
	// Mean squared error of resolved forecasts, in [0, 1]; lower is better.
	BrierScore float64 `json:"brierScore"`
	// Number of resolved forecasts the Brier score covers.
	ForecastCount int `json:"forecastCount"`
	// Fraction of resolved decisions that succeeded, in [0, 1].
	DecisionSuccessRate float64 `json:"decisionSuccessRate"`
	// Number of decisions with a recorded outcome.
	ResolvedDecisionCount int `json:"resolvedDecisionCount"`
}

type TransitionDecisionInput struct {
	ID     string         `json:"id"`
	Status DecisionStatus `json:"status"`
}

type UpdateAssumptionInput struct {
	ID         string  `json:"id"`
	Statement  string  `json:"statement"`
	Confidence float64 `json:"confidence"`
}

type UpdateDecisionInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type UpdateEvidenceInput struct {
	ID         string             `json:"id"`
	SourceType EvidenceSourceType `json:"sourceType"`
	SourceURL  *string            `json:"sourceUrl,omitempty"`
	Content    string             `json:"content"`
}

type UpdatePredictionInput struct {
	ID          string     `json:"id"`
	Statement   string     `json:"statement"`
	Probability float64    `json:"probability"`
	ResolvesAt  *time.Time `json:"resolvesAt,omitempty"`
}

type UpdateProfileInput struct {
	Name string `json:"name"`
}

type UpdateProfilePayload struct {
	User       *User       `json:"user,omitempty"`
	UserErrors []UserError `json:"userErrors"`
}

// A user account.
type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// A recoverable, field-level error returned from a mutation.
type UserError struct {
	// The input field the error applies to, if any.
	Field *string `json:"field,omitempty"`
	// A human-readable description of the error.
	Message string `json:"message"`
	// A stable, machine-readable error code.
	Code string `json:"code"`
}

// Lifecycle status of a decision.
type DecisionStatus string

const (
	DecisionStatusDraft    DecisionStatus = "DRAFT"
	DecisionStatusActive   DecisionStatus = "ACTIVE"
	DecisionStatusDecided  DecisionStatus = "DECIDED"
	DecisionStatusArchived DecisionStatus = "ARCHIVED"
)

var AllDecisionStatus = []DecisionStatus{
	DecisionStatusDraft,
	DecisionStatusActive,
	DecisionStatusDecided,
	DecisionStatusArchived,
}

func (e DecisionStatus) IsValid() bool {
	switch e {
	case DecisionStatusDraft, DecisionStatusActive, DecisionStatusDecided, DecisionStatusArchived:
		return true
	}
	return false
}

func (e DecisionStatus) String() string {
	return string(e)
}

func (e *DecisionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DecisionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DecisionStatus", str)
	}
	return nil
}

func (e DecisionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DecisionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DecisionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// The kind of source a piece of evidence comes from.
type EvidenceSourceType string

const (
	EvidenceSourceTypeURL      EvidenceSourceType = "URL"
	EvidenceSourceTypeDocument EvidenceSourceType = "DOCUMENT"
	EvidenceSourceTypeNote     EvidenceSourceType = "NOTE"
	EvidenceSourceTypeDataset  EvidenceSourceType = "DATASET"
)

var AllEvidenceSourceType = []EvidenceSourceType{
	EvidenceSourceTypeURL,
	EvidenceSourceTypeDocument,
	EvidenceSourceTypeNote,
	EvidenceSourceTypeDataset,
}

func (e EvidenceSourceType) IsValid() bool {
	switch e {
	case EvidenceSourceTypeURL, EvidenceSourceTypeDocument, EvidenceSourceTypeNote, EvidenceSourceTypeDataset:
		return true
	}
	return false
}

func (e EvidenceSourceType) String() string {
	return string(e)
}

func (e *EvidenceSourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EvidenceSourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EvidenceSourceType", str)
	}
	return nil
}

func (e EvidenceSourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EvidenceSourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EvidenceSourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Membership role within a team, ordered from most to least privileged.
type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleViewer Role = "VIEWER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
