package users

import (
	"context"
	stderrors "errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/platform/db"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/platform/db/sqlc"
	"github.com/michaelgavalas/decision-intelligence-os/backend/pkg/errors"
)

// pgUniqueViolation is the PostgreSQL SQLSTATE for a unique-constraint failure.
const pgUniqueViolation = "23505"

// CreateParams carries the fields required to insert a new user. The id is
// generated by the service and supplied here so the repository stays a thin
// persistence layer.
type CreateParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
}

// Repository is the persistence boundary for users. Every method takes a
// db.Querier so callers decide whether the operation joins an in-flight
// transaction (pass a tx) or runs standalone (pass the pool).
type Repository interface {
	Create(ctx context.Context, q db.Querier, p CreateParams) (User, error)
	GetByID(ctx context.Context, q db.Querier, id uuid.UUID) (User, error)
	GetByEmail(ctx context.Context, q db.Querier, email string) (User, error)
	UpdateName(ctx context.Context, q db.Querier, id uuid.UUID, name string) (User, error)
	ListByIDs(ctx context.Context, q db.Querier, ids []uuid.UUID) ([]User, error)
}

// repository is the sqlc-backed Repository implementation.
type repository struct{}

// NewRepository returns the default Repository.
func NewRepository() Repository {
	return repository{}
}

func (repository) Create(ctx context.Context, q db.Querier, p CreateParams) (User, error) {
	row, err := sqlc.New(q).CreateUser(ctx, sqlc.CreateUserParams{
		ID:           p.ID,
		Email:        p.Email,
		Name:         p.Name,
		PasswordHash: p.PasswordHash,
	})
	if err != nil {
		if isUniqueViolation(err) {
			return User{}, errors.Conflict("EMAIL_TAKEN", "email already registered")
		}
		return User{}, errors.Wrap(err, errors.KindInternal, "USER_CREATE_FAILED", "failed to create user")
	}
	return toUser(row), nil
}

func (repository) GetByID(ctx context.Context, q db.Querier, id uuid.UUID) (User, error) {
	row, err := sqlc.New(q).GetUserByID(ctx, id)
	if err != nil {
		if stderrors.Is(err, pgx.ErrNoRows) {
			return User{}, errors.NotFound("USER_NOT_FOUND", "user not found")
		}
		return User{}, errors.Wrap(err, errors.KindInternal, "USER_GET_FAILED", "failed to load user")
	}
	return toUser(row), nil
}

func (repository) GetByEmail(ctx context.Context, q db.Querier, email string) (User, error) {
	row, err := sqlc.New(q).GetUserByEmail(ctx, email)
	if err != nil {
		if stderrors.Is(err, pgx.ErrNoRows) {
			return User{}, errors.NotFound("USER_NOT_FOUND", "user not found")
		}
		return User{}, errors.Wrap(err, errors.KindInternal, "USER_GET_FAILED", "failed to load user")
	}
	return toUser(row), nil
}

func (repository) UpdateName(ctx context.Context, q db.Querier, id uuid.UUID, name string) (User, error) {
	row, err := sqlc.New(q).UpdateUserName(ctx, sqlc.UpdateUserNameParams{ID: id, Name: name})
	if err != nil {
		if stderrors.Is(err, pgx.ErrNoRows) {
			return User{}, errors.NotFound("USER_NOT_FOUND", "user not found")
		}
		return User{}, errors.Wrap(err, errors.KindInternal, "USER_UPDATE_FAILED", "failed to update user")
	}
	return toUser(row), nil
}

func (repository) ListByIDs(ctx context.Context, q db.Querier, ids []uuid.UUID) ([]User, error) {
	rows, err := sqlc.New(q).ListUsersByIDs(ctx, ids)
	if err != nil {
		return nil, errors.Wrap(err, errors.KindInternal, "USER_LIST_FAILED", "failed to list users")
	}
	out := make([]User, 0, len(rows))
	for _, r := range rows {
		out = append(out, toUser(r))
	}
	return out, nil
}

// toUser maps a generated sqlc row to the domain entity.
func toUser(r sqlc.User) User {
	return User{
		ID:           r.ID,
		Email:        r.Email,
		Name:         r.Name,
		PasswordHash: r.PasswordHash,
		CreatedAt:    r.CreatedAt,
		UpdatedAt:    r.UpdatedAt,
	}
}

// isUniqueViolation reports whether err is a PostgreSQL unique-constraint
// violation.
func isUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return stderrors.As(err, &pgErr) && pgErr.Code == pgUniqueViolation
}
