// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const teamCalibration = `-- name: TeamCalibration :many
SELECT
  LEAST(width_bucket(p.probability, 0, 1, 10), 10)::int AS bucket,
  AVG(p.probability)::float8 AS mean_predicted,
  AVG(CASE WHEN o.success THEN 1.0 ELSE 0.0 END)::float8 AS observed_frequency,
  COUNT(*) AS sample_size
FROM predictions p
JOIN decisions d ON d.id = p.decision_id
JOIN outcomes o ON o.decision_id = d.id
WHERE d.team_id = $1
GROUP BY bucket
ORDER BY bucket
`

type TeamCalibrationRow struct {
	Bucket            int32
	MeanPredicted     float64
	ObservedFrequency float64
	SampleSize        int64
}

// Reliability bins for a team's resolved forecasts: predictions grouped into
// deciles of predicted probability, with the mean predicted probability and the
// observed success frequency in each bin. A well-calibrated team has observed
// frequency tracking mean predicted probability across bins.
func (q *Queries) TeamCalibration(ctx context.Context, teamID uuid.UUID) ([]TeamCalibrationRow, error) {
	rows, err := q.db.Query(ctx, teamCalibration, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamCalibrationRow
	for rows.Next() {
		var i TeamCalibrationRow
		if err := rows.Scan(
			&i.Bucket,
			&i.MeanPredicted,
			&i.ObservedFrequency,
			&i.SampleSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamDecisionSuccessRate = `-- name: TeamDecisionSuccessRate :one
SELECT
  COALESCE(AVG(CASE WHEN o.success THEN 1.0 ELSE 0.0 END), 0)::float8 AS success_rate,
  COUNT(*) AS resolved_count
FROM decisions d
JOIN outcomes o ON o.decision_id = d.id
WHERE d.team_id = $1
`

type TeamDecisionSuccessRateRow struct {
	SuccessRate   float64
	ResolvedCount int64
}

// Fraction of a team's resolved decisions whose outcome succeeded, plus the
// number of resolved decisions. An empty team scores 0.
func (q *Queries) TeamDecisionSuccessRate(ctx context.Context, teamID uuid.UUID) (TeamDecisionSuccessRateRow, error) {
	row := q.db.QueryRow(ctx, teamDecisionSuccessRate, teamID)
	var i TeamDecisionSuccessRateRow
	err := row.Scan(&i.SuccessRate, &i.ResolvedCount)
	return i, err
}

const teamForecastMetrics = `-- name: TeamForecastMetrics :one
SELECT
  COALESCE(AVG(POWER(p.probability - (CASE WHEN o.success THEN 1 ELSE 0 END), 2)), 0)::float8 AS brier_score,
  COUNT(*) AS forecast_count
FROM predictions p
JOIN decisions d ON d.id = p.decision_id
JOIN outcomes o ON o.decision_id = d.id
WHERE d.team_id = $1
`

type TeamForecastMetricsRow struct {
	BrierScore    float64
	ForecastCount int64
}

// Brier score across a team's resolved forecasts: the mean squared error
// between each prediction's probability and the realized outcome (1 on success,
// 0 otherwise). Lower is better; an empty team scores 0. A prediction is
// resolved when its decision has an outcome.
func (q *Queries) TeamForecastMetrics(ctx context.Context, teamID uuid.UUID) (TeamForecastMetricsRow, error) {
	row := q.db.QueryRow(ctx, teamForecastMetrics, teamID)
	var i TeamForecastMetricsRow
	err := row.Scan(&i.BrierScore, &i.ForecastCount)
	return i, err
}
