// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assumptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssumption = `-- name: CreateAssumption :one
INSERT INTO assumptions (id, decision_id, statement, confidence)
VALUES ($1, $2, $3, $4)
RETURNING id, decision_id, statement, confidence, created_at, updated_at
`

type CreateAssumptionParams struct {
	ID         uuid.UUID
	DecisionID uuid.UUID
	Statement  string
	Confidence pgtype.Numeric
}

func (q *Queries) CreateAssumption(ctx context.Context, arg CreateAssumptionParams) (Assumption, error) {
	row := q.db.QueryRow(ctx, createAssumption,
		arg.ID,
		arg.DecisionID,
		arg.Statement,
		arg.Confidence,
	)
	var i Assumption
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Statement,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssumption = `-- name: DeleteAssumption :exec
DELETE FROM assumptions
WHERE id = $1
`

func (q *Queries) DeleteAssumption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssumption, id)
	return err
}

const getAssumptionByID = `-- name: GetAssumptionByID :one
SELECT id, decision_id, statement, confidence, created_at, updated_at FROM assumptions
WHERE id = $1
`

func (q *Queries) GetAssumptionByID(ctx context.Context, id uuid.UUID) (Assumption, error) {
	row := q.db.QueryRow(ctx, getAssumptionByID, id)
	var i Assumption
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Statement,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssumptionsByDecision = `-- name: ListAssumptionsByDecision :many
SELECT id, decision_id, statement, confidence, created_at, updated_at FROM assumptions
WHERE decision_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAssumptionsByDecision(ctx context.Context, decisionID uuid.UUID) ([]Assumption, error) {
	rows, err := q.db.Query(ctx, listAssumptionsByDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assumption
	for rows.Next() {
		var i Assumption
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Statement,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssumptionsByDecisionIDs = `-- name: ListAssumptionsByDecisionIDs :many
SELECT id, decision_id, statement, confidence, created_at, updated_at FROM assumptions
WHERE decision_id = ANY($1::uuid[])
ORDER BY decision_id, created_at DESC
`

func (q *Queries) ListAssumptionsByDecisionIDs(ctx context.Context, ids []uuid.UUID) ([]Assumption, error) {
	rows, err := q.db.Query(ctx, listAssumptionsByDecisionIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assumption
	for rows.Next() {
		var i Assumption
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Statement,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssumptionsByIDs = `-- name: ListAssumptionsByIDs :many
SELECT id, decision_id, statement, confidence, created_at, updated_at FROM assumptions
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListAssumptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Assumption, error) {
	rows, err := q.db.Query(ctx, listAssumptionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assumption
	for rows.Next() {
		var i Assumption
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Statement,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssumption = `-- name: UpdateAssumption :one
UPDATE assumptions
SET statement = $2,
    confidence = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, decision_id, statement, confidence, created_at, updated_at
`

type UpdateAssumptionParams struct {
	ID         uuid.UUID
	Statement  string
	Confidence pgtype.Numeric
}

func (q *Queries) UpdateAssumption(ctx context.Context, arg UpdateAssumptionParams) (Assumption, error) {
	row := q.db.QueryRow(ctx, updateAssumption, arg.ID, arg.Statement, arg.Confidence)
	var i Assumption
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Statement,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
