// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDecisionsByTeam = `-- name: CountDecisionsByTeam :one
SELECT count(*) FROM decisions
WHERE team_id = $1
`

func (q *Queries) CountDecisionsByTeam(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDecisionsByTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (id, team_id, owner_id, title, description, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at
`

type CreateDecisionParams struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
	Status      string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ID,
		arg.TeamID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecisionByID = `-- name: GetDecisionByID :one
SELECT id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at FROM decisions
WHERE id = $1
`

func (q *Queries) GetDecisionByID(ctx context.Context, id uuid.UUID) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecisionByID, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecisionsByIDs = `-- name: ListDecisionsByIDs :many
SELECT id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at FROM decisions
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListDecisionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByTeam = `-- name: ListDecisionsByTeam :many
SELECT id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at FROM decisions
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListDecisionsByTeamParams struct {
	TeamID uuid.UUID
	Limit  int32
}

func (q *Queries) ListDecisionsByTeam(ctx context.Context, arg ListDecisionsByTeamParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByTeam, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByTeamAfter = `-- name: ListDecisionsByTeamAfter :many
SELECT id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at FROM decisions
WHERE team_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListDecisionsByTeamAfterParams struct {
	TeamID    uuid.UUID
	CreatedAt time.Time
	ID        uuid.UUID
	Limit     int32
}

func (q *Queries) ListDecisionsByTeamAfter(ctx context.Context, arg ListDecisionsByTeamAfterParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByTeamAfter,
		arg.TeamID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDecision = `-- name: UpdateDecision :one
UPDATE decisions
SET title = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at
`

type UpdateDecisionParams struct {
	ID          uuid.UUID
	Title       string
	Description string
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, updateDecision, arg.ID, arg.Title, arg.Description)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDecisionStatus = `-- name: UpdateDecisionStatus :one
UPDATE decisions
SET status = $2,
    decided_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, team_id, owner_id, title, description, status, decided_at, created_at, updated_at
`

type UpdateDecisionStatusParams struct {
	ID        uuid.UUID
	Status    string
	DecidedAt pgtype.Timestamptz
}

func (q *Queries) UpdateDecisionStatus(ctx context.Context, arg UpdateDecisionStatusParams) (Decision, error) {
	row := q.db.QueryRow(ctx, updateDecisionStatus, arg.ID, arg.Status, arg.DecidedAt)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
