// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, aggregate_id, aggregate_type, event_type, payload, actor_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, aggregate_id, aggregate_type, event_type, payload, actor_id, occurred_at
`

type InsertEventParams struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	ActorID       *uuid.UUID
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.ActorID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.ActorID,
		&i.OccurredAt,
	)
	return i, err
}

const listEventsByAggregate = `-- name: ListEventsByAggregate :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, actor_id, occurred_at FROM events
WHERE aggregate_id = $1
ORDER BY occurred_at
`

func (q *Queries) ListEventsByAggregate(ctx context.Context, aggregateID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByAggregate, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.ActorID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
