// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO evidence (id, assumption_id, source_type, source_url, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, assumption_id, source_type, source_url, content, created_at, updated_at
`

type CreateEvidenceParams struct {
	ID           uuid.UUID
	AssumptionID uuid.UUID
	SourceType   string
	SourceUrl    *string
	Content      string
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, createEvidence,
		arg.ID,
		arg.AssumptionID,
		arg.SourceType,
		arg.SourceUrl,
		arg.Content,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AssumptionID,
		&i.SourceType,
		&i.SourceUrl,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvidence = `-- name: DeleteEvidence :exec
DELETE FROM evidence
WHERE id = $1
`

func (q *Queries) DeleteEvidence(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvidence, id)
	return err
}

const getEvidenceByID = `-- name: GetEvidenceByID :one
SELECT id, assumption_id, source_type, source_url, content, created_at, updated_at FROM evidence
WHERE id = $1
`

func (q *Queries) GetEvidenceByID(ctx context.Context, id uuid.UUID) (Evidence, error) {
	row := q.db.QueryRow(ctx, getEvidenceByID, id)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AssumptionID,
		&i.SourceType,
		&i.SourceUrl,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvidenceByAssumption = `-- name: ListEvidenceByAssumption :many
SELECT id, assumption_id, source_type, source_url, content, created_at, updated_at FROM evidence
WHERE assumption_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListEvidenceByAssumption(ctx context.Context, assumptionID uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByAssumption, assumptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.AssumptionID,
			&i.SourceType,
			&i.SourceUrl,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByAssumptionIDs = `-- name: ListEvidenceByAssumptionIDs :many
SELECT id, assumption_id, source_type, source_url, content, created_at, updated_at FROM evidence
WHERE assumption_id = ANY($1::uuid[])
ORDER BY assumption_id, created_at DESC
`

func (q *Queries) ListEvidenceByAssumptionIDs(ctx context.Context, ids []uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByAssumptionIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.AssumptionID,
			&i.SourceType,
			&i.SourceUrl,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceByIDs = `-- name: ListEvidenceByIDs :many
SELECT id, assumption_id, source_type, source_url, content, created_at, updated_at FROM evidence
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListEvidenceByIDs(ctx context.Context, ids []uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evidence
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.AssumptionID,
			&i.SourceType,
			&i.SourceUrl,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvidence = `-- name: UpdateEvidence :one
UPDATE evidence
SET source_type = $2,
    source_url = $3,
    content = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, assumption_id, source_type, source_url, content, created_at, updated_at
`

type UpdateEvidenceParams struct {
	ID         uuid.UUID
	SourceType string
	SourceUrl  *string
	Content    string
}

func (q *Queries) UpdateEvidence(ctx context.Context, arg UpdateEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, updateEvidence,
		arg.ID,
		arg.SourceType,
		arg.SourceUrl,
		arg.Content,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AssumptionID,
		&i.SourceType,
		&i.SourceUrl,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
