// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assumption struct {
	ID         uuid.UUID
	DecisionID uuid.UUID
	Statement  string
	Confidence pgtype.Numeric
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Decision struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Description string
	Status      string
	DecidedAt   pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Event struct {
	ID            uuid.UUID
	AggregateID   uuid.UUID
	AggregateType string
	EventType     string
	Payload       []byte
	ActorID       *uuid.UUID
	OccurredAt    time.Time
}

type Evidence struct {
	ID           uuid.UUID
	AssumptionID uuid.UUID
	SourceType   string
	SourceUrl    *string
	Content      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Outcome struct {
	ID         uuid.UUID
	DecisionID uuid.UUID
	Summary    string
	Success    bool
	ResolvedAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Prediction struct {
	ID          uuid.UUID
	DecisionID  uuid.UUID
	Statement   string
	Probability pgtype.Numeric
	ResolvesAt  pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RateLimit struct {
	Key         string
	Count       int32
	WindowStart time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	RevokedAt  pgtype.Timestamptz
	ReplacedBy *uuid.UUID
	CreatedAt  time.Time
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	TeamID    uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
