// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOutcomeByDecision = `-- name: GetOutcomeByDecision :one
SELECT id, decision_id, summary, success, resolved_at, created_at, updated_at FROM outcomes
WHERE decision_id = $1
`

func (q *Queries) GetOutcomeByDecision(ctx context.Context, decisionID uuid.UUID) (Outcome, error) {
	row := q.db.QueryRow(ctx, getOutcomeByDecision, decisionID)
	var i Outcome
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Summary,
		&i.Success,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutcomesByDecisionIDs = `-- name: ListOutcomesByDecisionIDs :many
SELECT id, decision_id, summary, success, resolved_at, created_at, updated_at FROM outcomes
WHERE decision_id = ANY($1::uuid[])
`

func (q *Queries) ListOutcomesByDecisionIDs(ctx context.Context, ids []uuid.UUID) ([]Outcome, error) {
	rows, err := q.db.Query(ctx, listOutcomesByDecisionIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outcome
	for rows.Next() {
		var i Outcome
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Summary,
			&i.Success,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomesByIDs = `-- name: ListOutcomesByIDs :many
SELECT id, decision_id, summary, success, resolved_at, created_at, updated_at FROM outcomes
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListOutcomesByIDs(ctx context.Context, ids []uuid.UUID) ([]Outcome, error) {
	rows, err := q.db.Query(ctx, listOutcomesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outcome
	for rows.Next() {
		var i Outcome
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Summary,
			&i.Success,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOutcome = `-- name: UpsertOutcome :one
INSERT INTO outcomes (id, decision_id, summary, success, resolved_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (decision_id) DO UPDATE
SET summary = EXCLUDED.summary,
    success = EXCLUDED.success,
    resolved_at = EXCLUDED.resolved_at,
    updated_at = now()
RETURNING id, decision_id, summary, success, resolved_at, created_at, updated_at
`

type UpsertOutcomeParams struct {
	ID         uuid.UUID
	DecisionID uuid.UUID
	Summary    string
	Success    bool
	ResolvedAt time.Time
}

func (q *Queries) UpsertOutcome(ctx context.Context, arg UpsertOutcomeParams) (Outcome, error) {
	row := q.db.QueryRow(ctx, upsertOutcome,
		arg.ID,
		arg.DecisionID,
		arg.Summary,
		arg.Success,
		arg.ResolvedAt,
	)
	var i Outcome
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Summary,
		&i.Success,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
