// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	CountDecisionsByTeam(ctx context.Context, teamID uuid.UUID) (int64, error)
	CountTeamAdmins(ctx context.Context, teamID uuid.UUID) (int64, error)
	CreateAssumption(ctx context.Context, arg CreateAssumptionParams) (Assumption, error)
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error)
	CreatePrediction(ctx context.Context, arg CreatePredictionParams) (Prediction, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAssumption(ctx context.Context, id uuid.UUID) error
	DeleteEvidence(ctx context.Context, id uuid.UUID) error
	GetAssumptionByID(ctx context.Context, id uuid.UUID) (Assumption, error)
	GetDecisionByID(ctx context.Context, id uuid.UUID) (Decision, error)
	GetEvidenceByID(ctx context.Context, id uuid.UUID) (Evidence, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMember, error)
	GetOutcomeByDecision(ctx context.Context, decisionID uuid.UUID) (Outcome, error)
	GetPredictionByID(ctx context.Context, id uuid.UUID) (Prediction, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	ListAssumptionsByDecision(ctx context.Context, decisionID uuid.UUID) ([]Assumption, error)
	ListAssumptionsByDecisionIDs(ctx context.Context, ids []uuid.UUID) ([]Assumption, error)
	ListAssumptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Assumption, error)
	ListDecisionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Decision, error)
	ListDecisionsByTeam(ctx context.Context, arg ListDecisionsByTeamParams) ([]Decision, error)
	ListDecisionsByTeamAfter(ctx context.Context, arg ListDecisionsByTeamAfterParams) ([]Decision, error)
	ListEventsByAggregate(ctx context.Context, aggregateID uuid.UUID) ([]Event, error)
	ListEvidenceByAssumption(ctx context.Context, assumptionID uuid.UUID) ([]Evidence, error)
	ListEvidenceByAssumptionIDs(ctx context.Context, ids []uuid.UUID) ([]Evidence, error)
	ListEvidenceByIDs(ctx context.Context, ids []uuid.UUID) ([]Evidence, error)
	ListMembersByTeam(ctx context.Context, teamID uuid.UUID) ([]TeamMember, error)
	ListMembersByTeamIDs(ctx context.Context, teamIds []uuid.UUID) ([]TeamMember, error)
	ListOutcomesByDecisionIDs(ctx context.Context, ids []uuid.UUID) ([]Outcome, error)
	ListOutcomesByIDs(ctx context.Context, ids []uuid.UUID) ([]Outcome, error)
	ListPredictionsByDecision(ctx context.Context, decisionID uuid.UUID) ([]Prediction, error)
	ListPredictionsByDecisionIDs(ctx context.Context, ids []uuid.UUID) ([]Prediction, error)
	ListPredictionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Prediction, error)
	ListTeamsByIDs(ctx context.Context, ids []uuid.UUID) ([]Team, error)
	ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error)
	ListUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]User, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error)
	// Reliability bins for a team's resolved forecasts: predictions grouped into
	// deciles of predicted probability, with the mean predicted probability and the
	// observed success frequency in each bin. A well-calibrated team has observed
	// frequency tracking mean predicted probability across bins.
	TeamCalibration(ctx context.Context, teamID uuid.UUID) ([]TeamCalibrationRow, error)
	// Fraction of a team's resolved decisions whose outcome succeeded, plus the
	// number of resolved decisions. An empty team scores 0.
	TeamDecisionSuccessRate(ctx context.Context, teamID uuid.UUID) (TeamDecisionSuccessRateRow, error)
	// Brier score across a team's resolved forecasts: the mean squared error
	// between each prediction's probability and the realized outcome (1 on success,
	// 0 otherwise). Lower is better; an empty team scores 0. A prediction is
	// resolved when its decision has an outcome.
	TeamForecastMetrics(ctx context.Context, teamID uuid.UUID) (TeamForecastMetricsRow, error)
	UpdateAssumption(ctx context.Context, arg UpdateAssumptionParams) (Assumption, error)
	UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error)
	UpdateDecisionStatus(ctx context.Context, arg UpdateDecisionStatusParams) (Decision, error)
	UpdateEvidence(ctx context.Context, arg UpdateEvidenceParams) (Evidence, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (TeamMember, error)
	UpdatePrediction(ctx context.Context, arg UpdatePredictionParams) (Prediction, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpsertOutcome(ctx context.Context, arg UpsertOutcomeParams) (Outcome, error)
}

var _ Querier = (*Queries)(nil)
