// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, role, created_at
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countTeamAdmins = `-- name: CountTeamAdmins :one
SELECT count(*) FROM team_members
WHERE team_id = $1 AND role = 'admin'
`

func (q *Queries) CountTeamAdmins(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamAdmins, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateTeamParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT team_id, user_id, role, created_at FROM team_members
WHERE team_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_at, updated_at FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersByTeam = `-- name: ListMembersByTeam :many
SELECT team_id, user_id, role, created_at FROM team_members
WHERE team_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembersByTeam(ctx context.Context, teamID uuid.UUID) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listMembersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByTeamIDs = `-- name: ListMembersByTeamIDs :many
SELECT team_id, user_id, role, created_at FROM team_members
WHERE team_id = ANY($1::uuid[])
ORDER BY team_id, created_at
`

func (q *Queries) ListMembersByTeamIDs(ctx context.Context, teamIds []uuid.UUID) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listMembersByTeamIDs, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByIDs = `-- name: ListTeamsByIDs :many
SELECT id, name, created_at, updated_at FROM teams
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListTeamsByIDs(ctx context.Context, ids []uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT teams.id, teams.name, teams.created_at, teams.updated_at
FROM teams
JOIN team_members ON team_members.team_id = teams.id
WHERE team_members.user_id = $1
ORDER BY teams.created_at
`

func (q *Queries) ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE team_members
SET role = $3
WHERE team_id = $1 AND user_id = $2
RETURNING team_id, user_id, role, created_at
`

type UpdateMemberRoleParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
