package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
)

// SummarizeEvidence is the resolver for the summarizeEvidence field. It first
// loads the evidence through the authorized service (so the caller's access is
// checked) and then asks the AI service to summarize its content. When AI is
// disabled the service returns FEATURE_DISABLED, which surfaces as a transport
// error; that is acceptable for these optional fields.
func (r *mutationResolver) SummarizeEvidence(ctx context.Context, evidenceID string) (*string, error) {
	id, err := parseID(evidenceID)
	if err != nil {
		return nil, err
	}
	ev, err := r.EvidenceSvc.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	summary, err := r.AI.SummarizeEvidence(ctx, ev.Content)
	if err != nil {
		return nil, err
	}
	return &summary, nil
}

// CritiqueAssumption is the resolver for the critiqueAssumption field.
func (r *mutationResolver) CritiqueAssumption(ctx context.Context, assumptionID string) (*string, error) {
	id, err := parseID(assumptionID)
	if err != nil {
		return nil, err
	}
	assumption, err := r.Assumptions.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	critique, err := r.AI.CritiqueAssumption(ctx, assumption.Statement)
	if err != nil {
		return nil, err
	}
	return &critique, nil
}

// DetectBias is the resolver for the detectBias field.
func (r *mutationResolver) DetectBias(ctx context.Context, text string) (*model.BiasReport, error) {
	report, err := r.AI.DetectBias(ctx, text)
	if err != nil {
		return nil, err
	}
	return toBiasReport(report), nil
}
