package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
)

// TeamMetrics is the resolver for the teamMetrics field.
func (r *queryResolver) TeamMetrics(ctx context.Context, teamID string) (*model.TeamMetrics, error) {
	id, err := parseID(teamID)
	if err != nil {
		return nil, err
	}
	metrics, err := r.Analytics.TeamMetrics(ctx, id)
	if err != nil {
		return nil, err
	}
	return toTeamMetrics(metrics), nil
}

// Calibration is the resolver for the calibration field.
func (r *queryResolver) Calibration(ctx context.Context, teamID string) (*model.CalibrationReport, error) {
	id, err := parseID(teamID)
	if err != nil {
		return nil, err
	}
	report, err := r.Analytics.Calibration(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCalibrationReport(report), nil
}
