package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/loaders"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/assumptions"
)

// Decision is the resolver for the decision field.
func (r *assumptionResolver) Decision(ctx context.Context, obj *model.Assumption) (*model.Decision, error) {
	assumptionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	assumption, err := loaders.GetAssumption(ctx, assumptionID)
	if err != nil {
		return nil, err
	}
	decision, err := loaders.GetDecision(ctx, assumption.DecisionID)
	if err != nil {
		return nil, err
	}
	return toDecision(decision), nil
}

// Evidence is the resolver for the evidence field.
func (r *assumptionResolver) Evidence(ctx context.Context, obj *model.Assumption) ([]model.Evidence, error) {
	assumptionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	items, err := loaders.EvidenceByAssumption(ctx, assumptionID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Evidence, 0, len(items))
	for _, e := range items {
		out = append(out, *toEvidence(e))
	}
	return out, nil
}

// AddAssumption is the resolver for the addAssumption field.
func (r *mutationResolver) AddAssumption(ctx context.Context, input model.AddAssumptionInput) (*model.AssumptionPayload, error) {
	decisionID, err := parseID(input.DecisionID)
	if err != nil {
		return nil, err
	}
	assumption, err := r.Assumptions.Add(ctx, assumptions.AddInput{
		DecisionID: decisionID,
		Statement:  input.Statement,
		Confidence: input.Confidence,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AssumptionPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.AssumptionPayload{Assumption: toAssumption(assumption), UserErrors: noUserErrors()}, nil
}

// UpdateAssumption is the resolver for the updateAssumption field.
func (r *mutationResolver) UpdateAssumption(ctx context.Context, input model.UpdateAssumptionInput) (*model.AssumptionPayload, error) {
	assumptionID, err := parseID(input.ID)
	if err != nil {
		return nil, err
	}
	assumption, err := r.Assumptions.Update(ctx, assumptionID, input.Statement, input.Confidence)
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AssumptionPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.AssumptionPayload{Assumption: toAssumption(assumption), UserErrors: noUserErrors()}, nil
}

// RemoveAssumption is the resolver for the removeAssumption field.
func (r *mutationResolver) RemoveAssumption(ctx context.Context, id string) (*model.DeletePayload, error) {
	assumptionID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	if err := r.Assumptions.Remove(ctx, assumptionID); err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.DeletePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.DeletePayload{Success: true, UserErrors: noUserErrors()}, nil
}

// Assumption returns graph.AssumptionResolver implementation.
func (r *Resolver) Assumption() graph.AssumptionResolver { return &assumptionResolver{r} }

type assumptionResolver struct{ *Resolver }
