package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/auth"
	"github.com/michaelgavalas/decision-intelligence-os/backend/pkg/errors"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	result, err := r.Auth.Register(ctx, auth.RegisterInput{
		Email:    input.Email,
		Name:     input.Name,
		Password: input.Password,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AuthPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	if err := r.setAuthCookies(ctx, result.RefreshToken); err != nil {
		return nil, err
	}
	return authPayload(result), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	result, err := r.Auth.Login(ctx, input.Email, input.Password, rateKey(ctx))
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AuthPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	if err := r.setAuthCookies(ctx, result.RefreshToken); err != nil {
		return nil, err
	}
	return authPayload(result), nil
}

// RefreshToken is the resolver for the refreshToken field. An explicit token
// argument (used by API and mobile clients) is trusted directly. Browser
// clients omit it; the token is then read from the httpOnly cookie and the
// request is verified against the double-submit CSRF token.
func (r *mutationResolver) RefreshToken(ctx context.Context, token *string) (*model.AuthPayload, error) {
	var raw string
	if token != nil && *token != "" {
		raw = *token
	} else {
		raw = readRefreshCookie(ctx)
		if raw == "" {
			return nil, errors.Unauthenticated("NO_REFRESH", "no refresh token provided")
		}
		if err := verifyCSRF(ctx); err != nil {
			return nil, err
		}
	}

	result, err := r.Auth.Refresh(ctx, raw)
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AuthPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	if err := r.setAuthCookies(ctx, result.RefreshToken); err != nil {
		return nil, err
	}
	return authPayload(result), nil
}

// Logout is the resolver for the logout field. The token comes from the
// argument when supplied, otherwise from the httpOnly refresh cookie. Both auth
// cookies are cleared regardless.
func (r *mutationResolver) Logout(ctx context.Context, token *string) (bool, error) {
	var raw string
	if token != nil && *token != "" {
		raw = *token
	} else {
		raw = readRefreshCookie(ctx)
	}
	if err := r.Auth.Logout(ctx, raw); err != nil {
		return false, err
	}
	r.clearAuthCookies(ctx)
	return true, nil
}
