package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/loaders"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/decisions"
	"github.com/michaelgavalas/decision-intelligence-os/backend/pkg/pagination"
)

// Owner is the resolver for the owner field.
func (r *decisionResolver) Owner(ctx context.Context, obj *model.Decision) (*model.User, error) {
	decisionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	decision, err := loaders.GetDecision(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	owner, err := loaders.GetUser(ctx, decision.OwnerID)
	if err != nil {
		return nil, err
	}
	return toUser(owner), nil
}

// Team is the resolver for the team field.
func (r *decisionResolver) Team(ctx context.Context, obj *model.Decision) (*model.Team, error) {
	decisionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	decision, err := loaders.GetDecision(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	team, err := loaders.GetTeam(ctx, decision.TeamID)
	if err != nil {
		return nil, err
	}
	return toTeam(team), nil
}

// Assumptions is the resolver for the assumptions field.
func (r *decisionResolver) Assumptions(ctx context.Context, obj *model.Decision) ([]model.Assumption, error) {
	decisionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	items, err := loaders.AssumptionsByDecision(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Assumption, 0, len(items))
	for _, a := range items {
		out = append(out, *toAssumption(a))
	}
	return out, nil
}

// Predictions is the resolver for the predictions field.
func (r *decisionResolver) Predictions(ctx context.Context, obj *model.Decision) ([]model.Prediction, error) {
	decisionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	items, err := loaders.PredictionsByDecision(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Prediction, 0, len(items))
	for _, p := range items {
		out = append(out, *toPrediction(p))
	}
	return out, nil
}

// Outcome is the resolver for the outcome field.
func (r *decisionResolver) Outcome(ctx context.Context, obj *model.Decision) (*model.Outcome, error) {
	decisionID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	outcome, err := loaders.OutcomeByDecision(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	if outcome == nil {
		return nil, nil
	}
	return toOutcome(*outcome), nil
}

// CreateDecision is the resolver for the createDecision field.
func (r *mutationResolver) CreateDecision(ctx context.Context, input model.CreateDecisionInput) (*model.DecisionPayload, error) {
	teamID, err := parseID(input.TeamID)
	if err != nil {
		return nil, err
	}
	decision, err := r.Decisions.Create(ctx, decisions.CreateInput{
		TeamID:      teamID,
		Title:       input.Title,
		Description: input.Description,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.DecisionPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	r.publishDecisionUpdated(ctx, decision.TeamID, decision.ID)
	return &model.DecisionPayload{Decision: toDecision(decision), UserErrors: noUserErrors()}, nil
}

// UpdateDecision is the resolver for the updateDecision field.
func (r *mutationResolver) UpdateDecision(ctx context.Context, input model.UpdateDecisionInput) (*model.DecisionPayload, error) {
	decisionID, err := parseID(input.ID)
	if err != nil {
		return nil, err
	}
	decision, err := r.Decisions.Update(ctx, decisionID, decisions.UpdateInput{
		Title:       input.Title,
		Description: input.Description,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.DecisionPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	r.publishDecisionUpdated(ctx, decision.TeamID, decision.ID)
	return &model.DecisionPayload{Decision: toDecision(decision), UserErrors: noUserErrors()}, nil
}

// TransitionDecision is the resolver for the transitionDecision field.
func (r *mutationResolver) TransitionDecision(ctx context.Context, input model.TransitionDecisionInput) (*model.DecisionPayload, error) {
	decisionID, err := parseID(input.ID)
	if err != nil {
		return nil, err
	}
	decision, err := r.Decisions.Transition(ctx, decisionID, decisionStatusFromModel(input.Status))
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.DecisionPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	r.publishDecisionUpdated(ctx, decision.TeamID, decision.ID)
	return &model.DecisionPayload{Decision: toDecision(decision), UserErrors: noUserErrors()}, nil
}

// Decision is the resolver for the decision field.
func (r *queryResolver) Decision(ctx context.Context, id string) (*model.Decision, error) {
	decisionID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	// r.Resolver.Decisions disambiguates the embedded service field from the
	// promoted Decisions query-resolver method of the same name.
	decision, err := r.Resolver.Decisions.GetByID(ctx, decisionID)
	if err != nil {
		return nil, err
	}
	return toDecision(decision), nil
}

// Decisions is the resolver for the decisions field.
func (r *queryResolver) Decisions(ctx context.Context, teamID string, first *int, after *string) (*model.DecisionConnection, error) {
	id, err := parseID(teamID)
	if err != nil {
		return nil, err
	}
	conn, err := r.Resolver.Decisions.List(ctx, id, pagination.PageArgs{First: first, After: after})
	if err != nil {
		return nil, err
	}
	return toDecisionConnection(conn), nil
}

// Decision returns graph.DecisionResolver implementation.
func (r *Resolver) Decision() graph.DecisionResolver { return &decisionResolver{r} }

type decisionResolver struct{ *Resolver }
