package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/loaders"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/evidence"
)

// Assumption is the resolver for the assumption field.
func (r *evidenceResolver) Assumption(ctx context.Context, obj *model.Evidence) (*model.Assumption, error) {
	evidenceID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	ev, err := loaders.GetEvidence(ctx, evidenceID)
	if err != nil {
		return nil, err
	}
	assumption, err := loaders.GetAssumption(ctx, ev.AssumptionID)
	if err != nil {
		return nil, err
	}
	return toAssumption(assumption), nil
}

// AttachEvidence is the resolver for the attachEvidence field.
func (r *mutationResolver) AttachEvidence(ctx context.Context, input model.AttachEvidenceInput) (*model.EvidencePayload, error) {
	assumptionID, err := parseID(input.AssumptionID)
	if err != nil {
		return nil, err
	}
	ev, err := r.EvidenceSvc.Attach(ctx, evidence.AttachInput{
		AssumptionID: assumptionID,
		SourceType:   evidenceSourceTypeFromModel(input.SourceType),
		SourceURL:    input.SourceURL,
		Content:      input.Content,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.EvidencePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.EvidencePayload{Evidence: toEvidence(ev), UserErrors: noUserErrors()}, nil
}

// UpdateEvidence is the resolver for the updateEvidence field.
func (r *mutationResolver) UpdateEvidence(ctx context.Context, input model.UpdateEvidenceInput) (*model.EvidencePayload, error) {
	evidenceID, err := parseID(input.ID)
	if err != nil {
		return nil, err
	}
	ev, err := r.EvidenceSvc.Update(ctx, evidenceID, evidenceSourceTypeFromModel(input.SourceType), input.SourceURL, input.Content)
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.EvidencePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.EvidencePayload{Evidence: toEvidence(ev), UserErrors: noUserErrors()}, nil
}

// RemoveEvidence is the resolver for the removeEvidence field.
func (r *mutationResolver) RemoveEvidence(ctx context.Context, id string) (*model.DeletePayload, error) {
	evidenceID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	if err := r.EvidenceSvc.Remove(ctx, evidenceID); err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.DeletePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.DeletePayload{Success: true, UserErrors: noUserErrors()}, nil
}

// Evidence returns graph.EvidenceResolver implementation.
func (r *Resolver) Evidence() graph.EvidenceResolver { return &evidenceResolver{r} }

type evidenceResolver struct{ *Resolver }
