package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/loaders"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/internal/outcomes"
)

// RecordOutcome is the resolver for the recordOutcome field.
func (r *mutationResolver) RecordOutcome(ctx context.Context, input model.RecordOutcomeInput) (*model.OutcomePayload, error) {
	decisionID, err := parseID(input.DecisionID)
	if err != nil {
		return nil, err
	}
	resolvedAt := input.ResolvedAt
	outcome, err := r.Outcomes.Record(ctx, outcomes.RecordInput{
		DecisionID: decisionID,
		Summary:    input.Summary,
		Success:    input.Success,
		ResolvedAt: &resolvedAt,
	})
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.OutcomePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.OutcomePayload{Outcome: toOutcome(outcome), UserErrors: noUserErrors()}, nil
}

// Decision is the resolver for the decision field.
func (r *outcomeResolver) Decision(ctx context.Context, obj *model.Outcome) (*model.Decision, error) {
	outcomeID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	outcome, err := loaders.GetOutcome(ctx, outcomeID)
	if err != nil {
		return nil, err
	}
	decision, err := loaders.GetDecision(ctx, outcome.DecisionID)
	if err != nil {
		return nil, err
	}
	return toDecision(decision), nil
}

// Outcome returns graph.OutcomeResolver implementation.
func (r *Resolver) Outcome() graph.OutcomeResolver { return &outcomeResolver{r} }

type outcomeResolver struct{ *Resolver }
