package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"encoding/json"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
)

// DecisionUpdated is the resolver for the decisionUpdated field. It subscribes
// to the decision-update channel, filters events to the requested team, loads
// the changed decision under the subscription's authenticated context, and
// streams the mapped decision until the client disconnects.
func (r *subscriptionResolver) DecisionUpdated(ctx context.Context, teamID string) (<-chan *model.Decision, error) {
	wantTeam, err := parseID(teamID)
	if err != nil {
		return nil, err
	}

	events, err := r.Subscriber.Subscribe(ctx, decisionUpdatedChannel)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Decision, decisionSubscriptionBuffer)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case payload, ok := <-events:
				if !ok {
					return
				}
				var evt decisionEvent
				if jsonErr := json.Unmarshal([]byte(payload), &evt); jsonErr != nil {
					continue
				}
				if evt.TeamID != wantTeam.String() {
					continue
				}
				decisionID, idErr := parseID(evt.DecisionID)
				if idErr != nil {
					continue
				}
				decision, getErr := r.Decisions.GetByID(ctx, decisionID)
				if getErr != nil {
					continue
				}
				select {
				case out <- toDecision(decision):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}
