package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/loaders"
	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
)

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, input model.CreateTeamInput) (*model.CreateTeamPayload, error) {
	team, err := r.Teams.CreateTeam(ctx, input.Name)
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.CreateTeamPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.CreateTeamPayload{Team: toTeam(team), UserErrors: noUserErrors()}, nil
}

// AddTeamMember is the resolver for the addTeamMember field.
func (r *mutationResolver) AddTeamMember(ctx context.Context, input model.AddTeamMemberInput) (*model.AddTeamMemberPayload, error) {
	teamID, err := parseID(input.TeamID)
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.UserID)
	if err != nil {
		return nil, err
	}
	membership, err := r.Teams.AddMember(ctx, teamID, userID, roleFromModel(input.Role))
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.AddTeamMemberPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	m, err := toMembership(ctx, membership)
	if err != nil {
		return nil, err
	}
	return &model.AddTeamMemberPayload{Membership: m, UserErrors: noUserErrors()}, nil
}

// ChangeMemberRole is the resolver for the changeMemberRole field.
func (r *mutationResolver) ChangeMemberRole(ctx context.Context, input model.ChangeMemberRoleInput) (*model.ChangeMemberRolePayload, error) {
	teamID, err := parseID(input.TeamID)
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.UserID)
	if err != nil {
		return nil, err
	}
	membership, err := r.Teams.ChangeRole(ctx, teamID, userID, roleFromModel(input.Role))
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.ChangeMemberRolePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	m, err := toMembership(ctx, membership)
	if err != nil {
		return nil, err
	}
	return &model.ChangeMemberRolePayload{Membership: m, UserErrors: noUserErrors()}, nil
}

// RemoveTeamMember is the resolver for the removeTeamMember field.
func (r *mutationResolver) RemoveTeamMember(ctx context.Context, input model.RemoveTeamMemberInput) (*model.RemoveTeamMemberPayload, error) {
	teamID, err := parseID(input.TeamID)
	if err != nil {
		return nil, err
	}
	userID, err := parseID(input.UserID)
	if err != nil {
		return nil, err
	}
	if err := r.Teams.RemoveMember(ctx, teamID, userID); err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.RemoveTeamMemberPayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.RemoveTeamMemberPayload{Success: true, UserErrors: noUserErrors()}, nil
}

// MyTeams is the resolver for the myTeams field.
func (r *queryResolver) MyTeams(ctx context.Context) ([]model.Team, error) {
	teamList, err := r.Teams.ListMyTeams(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Team, 0, len(teamList))
	for _, t := range teamList {
		out = append(out, *toTeam(t))
	}
	return out, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	teamID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	// Authorize via membership: a non-member is forbidden. ListMembers performs
	// the membership check, and the team itself is then loaded through the
	// per-request loader.
	if _, err := r.Teams.ListMembers(ctx, teamID); err != nil {
		return nil, err
	}
	team, err := loaders.GetTeam(ctx, teamID)
	if err != nil {
		return nil, err
	}
	return toTeam(team), nil
}

// Members is the resolver for the members field.
func (r *teamResolver) Members(ctx context.Context, obj *model.Team) ([]model.Membership, error) {
	teamID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	members, err := r.Teams.ListMembers(ctx, teamID)
	if err != nil {
		return nil, err
	}
	out := make([]model.Membership, 0, len(members))
	for _, m := range members {
		mapped, mapErr := toMembership(ctx, m)
		if mapErr != nil {
			return nil, mapErr
		}
		out = append(out, *mapped)
	}
	return out, nil
}

// Team returns graph.TeamResolver implementation.
func (r *Resolver) Team() graph.TeamResolver { return &teamResolver{r} }

type teamResolver struct{ *Resolver }
