package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/michaelgavalas/decision-intelligence-os/backend/graph/model"
	"github.com/michaelgavalas/decision-intelligence-os/backend/pkg/authctx"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UpdateProfilePayload, error) {
	principal, err := authctx.Require(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.UpdateProfile(ctx, principal.UserID, input.Name)
	if err != nil {
		if ue, ok := toUserErrors(err); ok {
			return &model.UpdateProfilePayload{UserErrors: ue}, nil
		}
		return nil, err
	}
	return &model.UpdateProfilePayload{User: toUser(user), UserErrors: noUserErrors()}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	principal, err := authctx.Require(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.GetByID(ctx, principal.UserID)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}
